DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS job;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE html_job (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date_found TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  html TEXT NOT NULL

);

CREATE TABLE job (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  body TEXT NOT NULL
);